// Package detect decides what travels.
//
// The model is deliberately inverted. git already knows exactly which files belong to
// this developer and not to the project: the ones it ignores. So envmove starts from
// that whole set and subtracts, instead of starting from a list of filenames to match.
//
// Matching a list was tried first and does not scale. New AI tools ship new dot
// directories, and every one of them needed another pattern: .claude, .cursor,
// .opencode, .superpowers, and whatever arrives next. Subtracting junk does not have
// that problem, because junk is a short, stable, well known list.
//
// The previous behaviour is kept where it is still useful, as classification rather
// than as a gate: knowing that a file is a secret is worth telling the user, but it no
// longer decides whether the file travels.
package detect

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type Class string

const (
	// Carry means the file travels.
	Carry Class = "carry"
	// Skip means it stays here, and the reason is shown to the user.
	Skip Class = "skip"
)

type Candidate struct {
	Path   string // relative to the repository root
	Class  Class
	Reason string
	Size   int64
}

// MaxFileBytes is the size above which a file is left behind.
//
// Everything genuinely worth carrying is small: a .env, a settings file, a handover
// note. A local SQLite database can be hundreds of megabytes, travels to no useful end
// and is always regenerable. The limit exists so that a permissive default cannot turn
// into an accidental copy of a build artefact.
const MaxFileBytes = 8 << 20 // 8 MiB

// junkDirs are path segments that mean "this can be regenerated". Matched as whole
// segments, so a project called "build-tools" is never caught by "build".
var junkDirs = map[string]string{
	// dependency trees
	"node_modules":     "dependency directory",
	"bower_components": "dependency directory",
	"vendor":           "dependency directory",
	".venv":            "virtualenv",
	"venv":             "virtualenv",
	"env":              "virtualenv",
	".bundle":          "dependency directory",
	".pnp":             "dependency directory",

	// generated code. "generated" as a directory name is almost always machine output:
	// src/generated, lib/generated, app/generated. Measured against a real project,
	// its absence let twenty-four files of Prisma client through, which is the failure
	// a permissive default invites.
	"generated":     "generated code",
	"__generated__": "generated code",
	"gen":           "generated code",

	// build output
	".next":   "build output",
	".build":  "build output",
	"build":   "build output",
	"dist":    "build output",
	"out":     "build output",
	"target":  "build output",
	".output": "build output",
	"release": "build output",

	// caches
	".cache":             "cache",
	".turbo":             "cache",
	".parcel-cache":      "cache",
	".sass-cache":        "cache",
	".pytest_cache":      "cache",
	".mypy_cache":        "cache",
	".ruff_cache":        "cache",
	".gradle":            "cache",
	".terraform":         "cache",
	"__pycache__":        "cache",
	".ipynb_checkpoints": "cache",

	// test and coverage output
	"coverage":    "coverage output",
	".nyc_output": "coverage output",
	"htmlcov":     "coverage output",
	".tox":        "test output",
	".idea":       "editor state",
	".vscode":     "editor state",
	".DS_Store":   "macOS metadata",
	".history":    "editor history",

	// local deployment and CI state
	".vercel":           "hosting CLI state",
	".netlify":          "hosting CLI state",
	".terraform.lock.d": "provider lock",
}

// junkGlobs are basenames that are never worth carrying.
var junkGlobs = map[string]string{
	// generated code
	"tsconfig.tsbuildinfo": "generated build metadata",
	"next-env.d.ts":        "generated by Next.js",
	"*.pb.go":              "generated protobuf code",
	"*_pb2.py":             "generated protobuf code",
	"*.pb.cc":              "generated protobuf code",
	"*.generated.*":        "generated code",
	"*.g.dart":             "generated code",
	"*.freezed.dart":       "generated code",

	// logs and dumps
	"*.log":           "log file",
	"npm-debug.log*":  "log file",
	"yarn-error.log*": "log file",
	"*.dump":          "core dump",
	"core":            "core dump",

	// OS cruft
	".DS_Store":       "macOS metadata",
	"Thumbs.db":       "Windows metadata",
	"ehthumbs.db":     "Windows metadata",
	"Desktop.ini":     "Windows metadata",
	".Spotlight-V100": "macOS metadata",
	".Trashes":        "macOS metadata",

	// local databases, regenerable from migrations
	"*.sqlite":     "local database",
	"*.sqlite3":    "local database",
	"*.db-journal": "local database",
}

// secretPatterns do not gate anything. They only explain to the user why a file that
// travels is worth a second look.
var secretPatterns = []string{
	".env", ".env.*", "*.env",
	"*.pem", "*.key", "*.p12", "*.pfx",
	"credentials.json", "credentials.*",
	".npmrc", ".netrc", ".pypirc",
	"*.secret", "secrets.json",
}

// agentPatterns likewise: a label, not a gate.
var agentPatterns = []string{
	"AGENTS.md", "CLAUDE.md", "GEMINI.md",
	".aider.conf.yml",
	"HANDOVER*", "*HANDOVER*.md",
	"*ROADMAP*", "*PLAN*.md", "*PROGRESS*", "*NOTES*.md",
	"TODO*", "TASKS*",
	".claude/**", ".cursor/**", ".opencode/**", ".superpowers/**",
	"notes/**", "tasks/**", "decisions/**", "journal/**",
}

// machineLocal are per machine by construction. The agent hooks live in
// .claude/settings.local.json precisely because it is never committed, so carrying it
// would move a path that only resolves where it was written.
var machineLocal = []string{
	".claude/settings.local.json",
	".cursor/rules/envmove.mdc",
	"**/settings.local.json",
}

// Scan classifies every gitignored path in the repository.
func Scan(root string) ([]Candidate, error) {
	paths, err := ignoredPaths(root)
	if err != nil {
		return nil, err
	}

	ignore, err := loadIgnoreList(root)
	if err != nil {
		return nil, err
	}

	out := make([]Candidate, 0, len(paths))
	for _, rel := range paths {
		out = append(out, classify(root, rel, ignore))
	}
	return out, nil
}

// classify is exported for testing, because every rule here is a decision about
// somebody's data and none of them should be untested.
func classify(root, rel string, ignore *ignoreList) Candidate {
	if reason, skip := exclude(rel, ignore); skip {
		return Candidate{Path: rel, Class: Skip, Reason: reason}
	}

	abs := filepath.Join(root, rel)
	info, err := os.Stat(abs)
	if err != nil {
		return Candidate{Path: rel, Class: Skip, Reason: "unreadable"}
	}
	if info.IsDir() {
		return Candidate{Path: rel, Class: Skip, Reason: "directory"}
	}
	if info.Size() > MaxFileBytes {
		return Candidate{
			Path:   rel,
			Class:  Skip,
			Size:   info.Size(),
			Reason: fmt.Sprintf("larger than %d MB", MaxFileBytes>>20),
		}
	}

	reason := "local project state"
	if _, ok := matchAny(rel, secretPatterns); ok {
		reason = "secret"
	} else if _, ok := matchAny(rel, agentPatterns); ok {
		reason = "agent state"
	}
	return Candidate{Path: rel, Class: Carry, Reason: reason, Size: info.Size()}
}

// exclude returns a reason when the path must stay put.
func exclude(rel string, ignore *ignoreList) (string, bool) {
	// envmove's own state is never negotiable. The baseline is encrypted and per
	// machine: carrying one would overwrite the receiving machine's baseline with the
	// sender's, and every later comparison would be against the wrong ancestor.
	if rel == ".envmove" || strings.HasPrefix(rel, ".envmove/") {
		return "envmove's own state", true
	}
	if rel == ".envmoveignore" {
		return "envmove configuration", true
	}

	if ignore.matches(rel) {
		return "listed in .envmoveignore", true
	}

	for _, segment := range segments(rel) {
		if reason, ok := junkDirs[segment]; ok {
			return reason, true
		}
	}

	base := filepath.Base(rel)
	for glob, reason := range junkGlobs {
		if ok, err := filepath.Match(glob, base); err == nil && ok {
			return reason, true
		}
	}

	for _, pattern := range machineLocal {
		if matchPath(rel, pattern) {
			return "machine-local", true
		}
	}

	return "", false
}

func segments(rel string) []string {
	return strings.Split(filepath.ToSlash(rel), "/")
}

// ignoredPaths lists every file git is not tracking, in one call.
//
// The directory-collapsing form of this was tried first and is wrong for the new model:
// it hides everything inside .claude/ or .superpowers/, which is exactly where the
// interesting files are. Listing files means the exclusion rules do the filtering, and
// git is fast enough even when a repository has forty thousand of them.
func ignoredPaths(root string) ([]string, error) {
	out, err := runGit(root, "ls-files", "--others", "--ignored", "--exclude-standard")
	if err != nil {
		return nil, err
	}
	var paths []string
	for _, line := range strings.Split(out, "\n") {
		line = strings.TrimSpace(line)
		if line != "" {
			paths = append(paths, filepath.ToSlash(line))
		}
	}
	return paths, nil
}

// ---------------------------------------------------------------- .envmoveignore

// ignoreList is a deny list and nothing else. There is no way to match a file in; that
// is git's job. Having only one direction keeps the file impossible to get wrong.
type ignoreList struct{ patterns []string }

func loadIgnoreList(root string) (*ignoreList, error) {
	raw, err := os.ReadFile(filepath.Join(root, ".envmoveignore"))
	if err != nil {
		return &ignoreList{}, nil
	}
	list := &ignoreList{}
	for _, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		list.patterns = append(list.patterns, strings.TrimSuffix(line, "/"))
	}
	return list, nil
}

func (l *ignoreList) matches(rel string) bool {
	if l == nil {
		return false
	}
	for _, pattern := range l.patterns {
		if pattern == rel || strings.HasPrefix(rel, pattern+"/") {
			return true
		}
		if ok, err := filepath.Match(pattern, rel); err == nil && ok {
			return true
		}
	}
	return false
}

// ---------------------------------------------------------------- helpers

// matchPath supports "dir/**" for a whole directory and "**/name" for a filename at any
// depth. Everything else is shell glob semantics, where * does not cross a path
// separator, so .env.* cannot swallow src/.env.prod.
func matchPath(rel, pattern string) bool {
	if rest, ok := strings.CutSuffix(pattern, "/**"); ok {
		return rel == rest || strings.HasPrefix(rel, rest+"/")
	}
	if rest, ok := strings.CutPrefix(pattern, "**/"); ok {
		return rel == rest || strings.HasSuffix(rel, "/"+rest)
	}
	ok, err := filepath.Match(pattern, rel)
	return err == nil && ok
}

func matchAny(rel string, patterns []string) (string, bool) {
	for _, p := range patterns {
		if matchPath(rel, p) {
			return p, true
		}
	}
	return "", false
}
